### ISSUE TITLE
LINUX SUPPOR ROLLOUT

### ISSUE THREAD

**Issue by snaildos** [snaildos/SnailFM-Application#16]
**LINUX SUPPORT HAS BEEN RELEASED**
For the sanity of the users, I need a tester.
If you have linux, please reply too this issue.
As of currently, known issues are:

- [x] Software dies on loadup- and the loading screen flickers and the main core app loads before the loading screen??
- [x] Graphics dont work properly.
- [ ] No installer. (sucks)
- [ ] Can't control much in linux version.
- [x] IIRC, Volume control doesn't work
Please update me with the replies of this issue.

**Comment by snaildos** [comment]
I need help here, Someone?

**Comment by MrDiamond64** [comment]
Why don't you use virtual box to test it out yourself?

**Comment by snaildos** [comment]
Lag
Besides, virtulization dosnt work as intended.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by snaildos** [comment]
Canceled, The app doesn't work as properly, expect rewrite soonTM. 
^w^

**Comment by snaildos** [comment]
Reponed, I need helpers! (I assume auto update should work with linux support, the only problem is that I don't have a build server..)

**Comment by snaildos** [comment]
Resolved. I created a build server and everything works now.
